accounts/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import profile, register
from .forms import UserLoginForm


app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html',
        authentication_form=UserLoginForm
    ), name='login'),
    path('register/', register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),

    path('reset/reset_password/',
         PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='reset_password'),
    path('reset/reset_password_sent/',
         PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/reset_password_complete/',
         PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),
         name='password_reset_complete'),
]

core/urls.py
from django.urls import path

from .views import *


app_name = 'core'
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('charts/', charts, name='charts'),
    path('shares/', shares_view, name='shares'),
    path('shares/search/', search_company, name='search'),
    path('shares/assets/price/', get_asset_price, name='price'),
    path('shares/details/<str:symbol>/', shares_detail, name='details'),
]

trustfuse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('', include('core.urls', namespace='core')),
    path('trading/', include('trading.urls', namespace='trading')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=13, unique=True)
    referer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='upline', blank=True, null=True)
    blocked = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} profile"

    def referral_link(self):
        return f"{settings.SITE_HOST}/auth/register?ref={self.user.username}"

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth.models import User

from core.enums import Country


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input-material',
            'placeholder': 'Enter your username'
        }
    ))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'input-material',
            'placeholder': 'Enter your password'
        }
    ))


class UserRegistrationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Create unique username. No spaces'
        }
    ))
    phone_number = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Enter Phone number for making payments'
        }
    ))
    country = forms.CharField()
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'placeholder': 'Enter Email Address'
        }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Create a strong password',
            'class': 'label-material'
        }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Confirm password'
        }
    ))

    class Meta:
        model = User
        fields = ('country', 'email', 'phone_number', 'username', 'password1', 'password2')

accounts/views.py
import random

import phonenumbers
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from accounts.forms import UserRegistrationForm
from accounts.models import Profile
from core.enums import Country


def profile(request):
    return


def register(request):
    form = UserRegistrationForm()
    ref = request.GET.get('ref')
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            error = 0
            u_country = form.cleaned_data['country']
            u_phone = phonenumbers.parse(form.cleaned_data['phone_number'], u_country)
            phone = phonenumbers.format_number(u_phone, phonenumbers.PhoneNumberFormat.E164)
            exists_phone = Profile.objects.filter(phone_number=phone)
            if exists_phone:
                messages.warning(request, 'Phone number exists with another account')
                error = 1

            if error == 0:
                user = form.save()
                print("after saving...")
                user.refresh_from_db()
                if ref:
                    usr = User.objects.filter(username=ref)
                    if usr:
                        user.profile.referer = usr[0]
                else:
                    x = random.choice(range(0, 3))
                    if x == 2:
                        user.profile.referer = User.objects.get(id=1)
                user.profile.phone_number = phone
                user.email = form.cleaned_data['email']
                user.save()
                user.profile.save()
                messages.info(request, 'USER REGISTERED SUCCESSFULLY')
                return redirect('login')
            else:
                messages.warning(request, 'You have an error in your input. Check and try again')
        else:
            errors = form.errors
            messages.warning(request, errors)

    context = {
        'form': form
    }
    if ref:
        usr = User.objects.filter(username=ref)
        if usr.exists():
            messages.info(request, f'You have been referred by {usr.first().username}')
            context['referer'] = usr.first().username

    return render(request, 'accounts/register.html', context)

accounts/templates/accounts/activate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="col-lg-6">
        <div class="block">
          <div class="title"><strong class="d-block">Activate Your Account To Continue</strong></div>
          <div class="block-body">
              <div class="alert">
                  <div class="p-3">
                      <ul class="list-group">
                          <li>In order to continue enjoying the services, You need to activate your account</li>
                          <li>After sending the activation fee, send your proof of payment to admin for confirmation</li>
                          <li>You will now enjoy to other services</li>
                      </ul>
                  </div>
              </div>
              <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Procedure for activation</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-description">Send Tsh. 15000 to 255745383928 (HAWA RAMADHANI MCHOPA)</p>
                        <input type="text" id="phoneInput" class="form-control" value="255745383928" readonly="readonly">
                        <div class="mt-3">
                          <button id="phone-copy-button" type="button" class="btn btn-info btn-clipboard" onclick="myFunction()">Click to copy Phone number</button>
                        </div>
                    </div>
                </div>
              </div>
          </div>
        </div>
      </div>
{% endblock %}

{% block custom_script %}

<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'js/charts-home.js' %}"></script>

    <script>

        function myFunction() {
            /* Get the text field */
            var copyText = document.getElementById("phoneInput");

            /* Select the text field */
            copyText.select();
            copyText.setSelectionRange(0, 99999); /*For mobile devices*/

            /* Copy the text inside the text field */
            document.execCommand("copy");

            $('#phone-copy-button').html('Phone number Copied!');

        }
    </script>

{% endblock %}

accounts/templates/accounts/downlines.html
{% extends 'base.html' %}

{% block content %}
<div class="col-lg-12 col-md-12">
    <div class="block margin-bottom-sm">
      <div class="title"><strong>Downlines</strong></div>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Username</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Date Joined</th>
              <th>Level</th>
            </tr>
          </thead>
          <tbody>
            {% for downline in downlines %}

               <tr>
                 <td>{{ forloop.counter }}</td>
                 <td>{{ downline.user.username }}</td>
                 <td>{{ downline.user.email }}</td>
                 <td>{{ downline.user.profile.phone_number }}</td>
                 <td>{{ downline.user.date_joined|timesince }} ago</td>
                 <td>{{ downline.level }}</td>
               </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Caremax::Login </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Custom Font Icons CSS-->
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    <!-- Google fonts - Muli-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <div class="login-page">
      <div class="container d-flex align-items-center">
        <div class="form-holder has-shadow">
          <div class="row">
            <!-- Logo & Information Panel-->
            <div class="col-lg-6">
              <div class="info d-flex align-items-center">
                <div class="content">
                  <div class="logo">
                    <h1>CAREMAX LOGIN</h1>
                  </div>
                  <p>Enter Your Username and Password To Log In</p>
                </div>
              </div>
            </div>
            <!-- Form Panel    -->
            <div class="col-lg-6 bg-white">
              <div class="form d-flex align-items-center">
                <div class="content">
                <div class="mb-4">

                    <span class="">Enter your credentials to log in</span>
                </div>
                  <form method="post" class="form-validate">
                    {% csrf_token %}
                    <div class="form-group">
                      <input id="login-username" type="text" name="username" required data-msg="Please enter your username" class="input-material">
                      <label for="login-username" class="label-material">User Name</label>
                    </div>
                    <div class="form-group">
                      <input id="login-password" type="password" name="password" required data-msg="Please enter your password" class="input-material">
                      <label for="login-password" class="label-material">Password</label>
                        {% if form.non_field_errors %}
                          <div class="alert alert-danger">
                            {{ form.non_field_errors }}
                          </div>
                        {% endif %}
                    </div><input type="submit" class="btn btn-primary" value="Login"/>
                    <!-- This should be submit button but I replaced it with <a> for demo purposes-->
                  </form><a href="{% url 'accounts:reset_password' %}" class="forgot-pass">Forgot Password?</a><br><small>Do not have an account? </small><a href="{% url 'accounts:register' %}" class="signup">Signup</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="copyrights text-center">
         <p>2021 &copy; CareMax. Designed by <a target="_blank" href="https://ondiekisteven.github.io">Somwaki</a>.</p>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-validation/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
  </body>
</html>

accounts/templates/accounts/password_reset_complete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dark Bootstrap Admin </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Custom Font Icons CSS-->
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    <!-- Google fonts - Muli-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <div class="login-page">
      <div class="container d-flex align-items-center">
        <div class="form-holder has-shadow">
          <div class="row">
            <!-- Logo & Information Panel-->
            <div class="col-lg-6">
              <div class="info d-flex align-items-center">
                <div class="content">
                  <div class="logo">
                    <h1>RESET COMPLETE</h1>
                  </div>
                  <p>Your Password has been changed successfully</p>
                </div>
              </div>
            </div>
            <!-- Form Panel    -->
            <div class="col-lg-6 bg-white">
              <div class="form d-flex align-items-center">
                <div class="content">
                  <div class="alert-info p-3">
                      <p>Your password has been reset. You may go ahead and <a href="{% url 'login' %}">Login</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="copyrights text-center">
         <p>2021 &copy; CareMax. Designed by <a target="_blank" href="https://ondiekisteven.github.io">Somwaki</a>.</p>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-validation/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
  </body>
</html>

accounts/templates/accounts/password_reset_confirm.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dark Bootstrap Admin </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Custom Font Icons CSS-->
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    <!-- Google fonts - Muli-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <div class="login-page">
      <div class="container d-flex align-items-center">
        <div class="form-holder has-shadow">
          <div class="row">
            <!-- Logo & Information Panel-->
            <div class="col-lg-6">
              <div class="info d-flex align-items-center">
                <div class="content">
                  <div class="logo">
                    <h1>LOGIN</h1>
                  </div>
                  <p>Enter Your Username and Password To Log In</p>
                </div>
              </div>
            </div>
            <!-- Form Panel    -->
            <div class="col-lg-6 bg-white">
              <div class="form d-flex align-items-center">
                <div class="content">
                  <form method="post" class="form-validate">
                    {% csrf_token %}
                    <div class="form-group">
                      <input id="login-username" type="password" name="password1" required data-msg="Please enter new password" class="input-material">
                      <label for="login-username" class="label-material">Password</label>
                    </div>
                    <div class="form-group">
                      <input id="login-password" type="password" name="password" required data-msg="Please re-enter the password" class="input-material">
                      <label for="login-password" class="label-material">Confirm Password</label>
                        {% if form.non_field_errors %}
                          <div class="alert alert-danger">
                            {{ form.non_field_errors }}
                          </div>
                        {% endif %}
                    </div><input type="submit" class="btn btn-primary" value="Reset Password"/>
                    <!-- This should be submit button but I replaced it with <a> for demo purposes-->
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="copyrights text-center">
         <p>2021 &copy; CareMax. Designed by <a target="_blank" href="https://ondiekisteven.github.io">Somwaki</a>.</p>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-validation/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
  </body>
</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="col-lg-6">
    <div class="block">
      <div class="title"><strong class="d-block">Profile</strong><span class="d-block"></span></div>
      <div class="block-body">
        <form class="form-horizontal">
          <div class="form-group row">
            <label class="col-sm-3 form-control-label">Username</label>
            <div class="col-sm-9">
              <input id="inputHorizontalSuccess" type="email" readonly value="{{ user.username }}" class="form-control form-control-success">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 form-control-label">Email Address</label>
            <div class="col-sm-9">
              <input id="inputHorizontalSuccess" type="text" readonly value="{{ user.email }}" class="form-control form-control-success">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 form-control-label">Phone Number</label>
            <div class="col-sm-9">
              <input id="inputHorizontalSuccess" type="text" readonly value="{{ user.profile.phone_number }}" class="form-control form-control-success">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 form-control-label">Date Joined</label>
            <div class="col-sm-9">
              <input id="inputHorizontalSuccess" type="text" readonly value="{{ user.date_joined }}" class="form-control form-control-success">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 form-control-label">Upline</label>
            <div class="col-sm-9">
              <input id="inputHorizontalWarning" type="text" readonly value="{{ user.profile.referer.username }}" class="form-control form-control-warning">
            </div>
          </div>

        </form>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Caremax::Login </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Custom Font Icons CSS-->
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    <!-- Google fonts - Muli-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <div class="login-page">
      <div class="container d-flex align-items-center">
        <div class="form-holder has-shadow">
          <div class="row">
            <!-- Logo & Information Panel-->
            <div class="col-lg-6">
              <div class="info d-flex align-items-center">
                <div class="content">
                  <div class="logo">
                    <h1>CAREMAX Registration</h1>
                  </div>
                  <p>Enter your details to create an account.</p>
                </div>
              </div>
            </div>
            <!-- Form Panel    -->
            <div class="col-lg-6 bg-white">
              <div class="form d-flex align-items-center">
                <div class="content">

                  <form method="post" class="form-validate">
                  {% if messages %}
                     {% for message in messages %}
                        <div class="row">
                                <div class="col-md-12">
                                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                        {{ message }}
                                    </div>
                                </div>
                            </div>
                     {% endfor %}
                    {% endif %}
                    <span class="">Fill In Your Details To Register</span>
                      {% csrf_token %}
                    <div class="form-group">
                      <input id="login-username" type="email" name="email" required data-msg="Please enter a valid email" class="input-material">
                      <label for="login-username" class="label-material">Email</label>
                    </div>
                    <div class="form-group">
                      <input id="login-username" type="text" name="phone_number" required data-msg="Please enter your phone" class="input-material">
                      <label for="login-username" class="label-material">Phone</label>
                    </div>
                    <div class="form-group">
                      <input id="login-username" type="text" name="username" required data-msg="Please enter your username" class="input-material">
                      <label for="login-username" class="label-material">Username</label>
                    </div>
                    <div class="form-group">
                      <input id="login-password" type="password" name="password1" required data-msg="Please enter your password" class="input-material">
                      <label for="login-password" class="label-material">Password</label>
                    </div>
                    <div class="form-group">
                      <input id="login-password" type="password" name="password2" required data-msg="Please enter your password" class="input-material">
                      <label for="login-password" class="label-material">Confirm Password</label>
                    </div>
                    <div class="form-group">
                      <input id="login-username" type="text" value="TZ" readonly name="country" class="input-material">
                      <label for="login-username" class="label-material">Country</label>
                    </div>
                      <input type="submit" id="login"  class="btn btn-primary" value="Register" />
                      {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                          {{ form.non_field_errors }}
                        </div>
                      {% endif %}
                    <!-- This should be submit button but I replaced it with <a> for demo purposes-->
                  </form><a href="{% url 'accounts:reset_password' %}" class="forgot-pass">Forgot Password?</a><br><small>Already have an account? </small><a href="{% url 'accounts:login' %}" class="signup">Login</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="copyrights text-center">
         <p>2021 &copy; CareMax. Designed by <a target="_blank" href="https://ondiekisteven.github.io">Somwaki</a>.</p>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-validation/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
  </body>
</html>