accounts/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import profile, register
from .forms import UserLoginForm


app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html',
        authentication_form=UserLoginForm
    ), name='login'),
    path('register/', register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),

    path('reset/reset_password/',
         PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='reset_password'),
    path('reset/reset_password_sent/',
         PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/reset_password_complete/',
         PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),
         name='password_reset_complete'),
]

core/urls.py
from django.urls import path

from .views import *


app_name = 'core'
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('charts/', charts, name='charts'),
    path('shares/', shares_view, name='shares'),
    path('shares/search/', search_company, name='search'),
    path('shares/assets/price/', get_asset_price, name='price'),
    path('shares/details/<str:symbol>/', shares_detail, name='details'),
]

trading/urls.py
from django.urls import path

from .views import *


app_name = 'trading'

urlpatterns = [
    path('investments/<int:pk>/receipt/', receipt_view, name='receipt'),
    path('investments/', investment_view, name='investments'),
    path('withdraw/', withdrawals_view, name='withdraw'),
    path('sell/', sell_view, name='sell'),
    path('sell/submit/', sell_shares, name='sell_submit'),
    path('buy/', buy_shares, name='buy_shares'),
]

trustfuse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('', include('core.urls', namespace='core')),
    path('trading/', include('trading.urls', namespace='trading')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=13, unique=True)
    referer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='upline', blank=True, null=True)
    blocked = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} profile"

    def referral_link(self):
        return f"{settings.SITE_HOST}/auth/register?ref={self.user.username}"

core/models.py
from django.db import models


class Share(models.Model):
    symbol = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    current_price = models.FloatField()
    avatar = models.ImageField(upload_to='shares', default='default.png')
    description = models.TextField(null=True, blank=True, default=None)

    def __str__(self):
        return self.symbol

trading/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from core.models import Share


class WithdrawStatus(models.IntegerChoices):

    PENDING = 0, _('Pending')
    APPROVED = 1, _('Approved')
    COMPLETED = 2, _('Completed')
    REJECTED = 3, _('Rejected')


class Base(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Investment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    share = models.ForeignKey(Share, on_delete=models.CASCADE, default=1)
    quantity = models.IntegerField(default=1)
    amount = models.FloatField()
    fees = models.FloatField(default=0)
    current_price = models.FloatField(default=0)
    investment_date = models.DateTimeField(default=timezone.now)

    def cost(self):
        return self.current_price * self.quantity

    def total_paid(self):
        return self.cost() + self.fees

    def net_earning(self):
        share_value = self.share.current_price
        return (share_value * self.quantity + self.fees) - (self.total_paid())


class Withdrawal(Base):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    amount = models.FloatField()
    status = models.IntegerField(choices=WithdrawStatus.choices, default=WithdrawStatus.PENDING)
    status_by = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='approver', null=True, blank=True)
    date_of_approval = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.user.username


class SoldShares(Base):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    share = models.ForeignKey(Share, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    amount_received = models.FloatField()

    def __str__(self):
        return self.user.username

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth.models import User

from core.enums import Country


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input-material',
            'placeholder': 'Enter your username'
        }
    ))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'input-material',
            'placeholder': 'Enter your password'
        }
    ))


class UserRegistrationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Create unique username. No spaces'
        }
    ))
    phone_number = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Enter Phone number for making payments'
        }
    ))
    country = forms.CharField()
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'placeholder': 'Enter Email Address'
        }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Create a strong password',
            'class': 'label-material'
        }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Confirm password'
        }
    ))

    class Meta:
        model = User
        fields = ('country', 'email', 'phone_number', 'username', 'password1', 'password2')

accounts/views.py
import random

import phonenumbers
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from accounts.forms import UserRegistrationForm
from accounts.models import Profile
from core.enums import Country


def profile(request):
    return


def register(request):
    form = UserRegistrationForm()
    ref = request.GET.get('ref')
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            error = 0
            u_country = form.cleaned_data['country']
            u_phone = phonenumbers.parse(form.cleaned_data['phone_number'], u_country)
            phone = phonenumbers.format_number(u_phone, phonenumbers.PhoneNumberFormat.E164)
            exists_phone = Profile.objects.filter(phone_number=phone)
            if exists_phone:
                messages.warning(request, 'Phone number exists with another account')
                error = 1

            if error == 0:
                user = form.save()
                print("after saving...")
                user.refresh_from_db()
                if ref:
                    usr = User.objects.filter(username=ref)
                    if usr:
                        user.profile.referer = usr[0]
                else:
                    x = random.choice(range(0, 3))
                    if x == 2:
                        user.profile.referer = User.objects.get(id=1)
                user.profile.phone_number = phone
                user.email = form.cleaned_data['email']
                user.save()
                user.profile.save()
                messages.info(request, 'USER REGISTERED SUCCESSFULLY')
                return redirect('login')
            else:
                messages.warning(request, 'You have an error in your input. Check and try again')
        else:
            errors = form.errors
            messages.warning(request, errors)

    context = {
        'form': form
    }
    if ref:
        usr = User.objects.filter(username=ref)
        if usr.exists():
            messages.info(request, f'You have been referred by {usr.first().username}')
            context['referer'] = usr.first().username

    return render(request, 'accounts/register.html', context)

core/views.py
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.db.models import Q
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404

from core.models import Share
from core.utils import Account


def dashboard(request):
    assets = Account(request.user)
    context = {
        'assets': assets.balance(),
        'value': assets.value()
    }
    return render(request, 'core/dashboard.html', context=context)


def charts(request):

    context = {
        'api_key': settings.PUSHY_APP_KEY,
        'cluster': settings.PUSHY_APP_CLUSTER,
    }
    return render(request, 'core/trading.html', context=context)


@csrf_exempt
def search_company(request):
    if request.is_ajax():
        search_term = request.POST['q']
        items = Share.objects.filter(Q(symbol__icontains=search_term) | Q(name__icontains=search_term))
        print(f"result: {items}")

        return JsonResponse(data=serializers.serialize('json', items), safe=False)


@csrf_exempt
def get_asset_price(request):
    if request.is_ajax():
        symbol = request.POST['q']
        share = get_object_or_404(Share, symbol=symbol)

        return JsonResponse(data=share.current_price, safe=False)


def shares_view(request):
    s = Share.objects.all()
    context = {
        'shares': s,
    }
    return render(request, 'core/shares_list.html', context=context)


@login_required
def shares_detail(request, symbol):
    try:
        s = Share.objects.get(symbol=symbol)
    except Share.DoesNotExist:
        return redirect('core:shares')
    context = {
        'share': s,
    }
    return render(request, 'core/shares_detail.html', context=context)

trading/views.py
from core.utils import Account
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

from core.models import Share
from trading.models import Investment, Withdrawal, SoldShares


@csrf_exempt
def buy_shares(request):
    if request.is_ajax():
        print(f'Incoming Request: {request.POST}')
        quantity = int(request.POST['quantity'])
        fees = int(request.POST['fees'])
        symbol = request.POST['symbol']

        share = Share.objects.get(symbol=symbol)
        user = request.user

        if quantity < 1:
            return HttpResponse('Shares bought cannot be 0',
                                status=HttpResponseBadRequest.status_code)

        unit_price = share.current_price
        amount = unit_price * quantity

        if amount + fees > user.wallet.amount:
            return HttpResponse('Not enough balance to invest this amount. Try a lower amount or deposit first',
                                status=HttpResponseBadRequest.status_code)
        investment = Investment.objects.create(
            user=user,
            amount=amount,
            share=share,
            quantity=quantity,
            fees=fees,
            current_price=share.current_price
        )
        return JsonResponse(data=serializers.serialize('json', [investment, ]), safe=False)


@login_required
def investment_view(request):
    invs = Investment.objects.filter(user=request.user)
    context = {
        'investments': invs
    }
    return render(request, 'trading/investments.html', context)


@login_required
def receipt_view(request, pk):
    try:
        inv = Investment.objects.get(pk=pk)
    except Investment.DoesNotExist:
        return redirect('trading:investments')
    return render(request, 'trading/receipt.html', {'investment': inv})


@login_required
def withdrawals_view(request):
    if request.method == 'POST':
        amount = int(request.POST['amount'])
        if 0 < amount <= request.user.wallet.amount:
            Withdrawal.objects.create(
                user=request.user,
                amount=amount,
            )
            messages.success(request, f'Successfully Withdrawn Ksh. {amount}')
            return redirect('trading:withdraw')
        else:
            messages.warning(request, "Invalid amount or not enough balance. Please try again later.")
    w = Withdrawal.objects.filter(user=request.user)
    context = {
        'withdrawals': w
    }
    return render(request, 'trading/withdrawals.html', context=context)


@csrf_exempt
def sell_shares(request):
    if request.is_ajax():
        asset = request.POST['asset']
        quantity = int(request.POST['quantity'])
        try:
            share = Share.objects.get(symbol=asset)
        except Share.DoesNotExist:
            return HttpResponse('Invalid Asset Selected.', HttpResponseBadRequest.status_code)
        # asst_qty = request.user.investment_set.filter(share=share).aggregate(Sum('quantity'))['quantity__sum'] or 0
        # print(asst_qty)
        acc = Account(request.user)
        asst_qty = 0
        for ast in acc.balance():
            if ast['share__symbol'] == share.symbol:
                asst_qty = ast['total_items']
                # print(f"asset {ast['share_symbol']} -> {ast['total_items']}")
                
        if 0 < quantity <= asst_qty:
            SoldShares.objects.create(
                user=request.user,
                share=share,
                quantity=quantity,
                amount_received=share.current_price * quantity
            )
            return HttpResponse(
                f"Successfully sold {quantity} {share.name} shares Worth Ksh. {share.current_price * quantity}",
                200
            )
        return HttpResponse(
            f"Invalid quantity. Either you dont have enough {share.name} shares or you entered invalid amount. Try again",
            HttpResponseBadRequest.status_code
        )


@login_required
def sell_view(request):
    acc = Account(request.user)
    items = [i for i in acc.balance() if i['total_items'] > 0]
    names = [i['share__symbol'] for i in items]

    context = {
        'shares': items,
        'names': names,
        'value': acc.value()
    }
    return render(request, 'trading/sell.html', context)

core/templates/core/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    {% include "head.html" %}
    <title>{% block title %}{% endblock %}</title>

  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:partials/_horizontal-navbar.html -->
      {% include 'navigation.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"> Available Companies To Invest In </h3>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Companies</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Invest</li>
                </ol>
              </nav>
            </div>
            {% if messages %}
              {% for message in messages %}
                <div class="row">
                  <div class="col-md-6 col-sm-12">
                    <div class="alert alert-{{ message.tags }}" role="alert"> {{ message }}. </div>
                  </div>
                </div>
              {% endfor %}
            {% endif %}
          {% block content %}

          {% endblock %}
        </div>
          <!-- content-wrapper ends -->
          {% include 'footer.html' %}
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    {% include 'scripts.html' %}
  {% block custom_script %}

  {% endblock %}

  </body>

<!-- Mirrored from www.bootstrapdash.com/demo/corona/jquery/template/classic-horizontal/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 03 Aug 2021 15:39:57 GMT -->
</html>

core/templates/core/shares_detail.html
{% extends 'core/index.html' %}
{% load static %}

{% block title %}
Share Detail
{% endblock %}

{% block custom_head %}

{% endblock %}

{% block custom_script %}
<script src="{% static 'js/holder.min.js' %}"></script>
<script src="{% static 'assets/js/alerts.js' %}"></script>
<script src="{% static 'assets/vendors/sweetalert/sweetalert2.all.min.js' %}"></script>
<script type="text/javascript">

{# DEFINING VARIABLES #}
const unit_price = {{ share.current_price }};
const amount_input = $('#amount');
const quantity_input = $('#quantity');
const user_balance = {{ user.wallet.amount }};
const amt = amount_input.val();
const btn = $('#invest_button');
let mSwal = function(type, message) {
    'use strict';
    Swal.fire({
        title: type + "!",
        text: message,
        icon: type,
    });

  }
amount_input.on('input', function(e) {
    if (amt >= 0) {
        quantity_input.prop('value', amt / unit_price);
    }
});
quantity_input.on('input', function (e) {
    const qty = quantity_input.val();
    var bal = user_balance - (qty * unit_price);
    if (bal < 0) {
        return
    }
    if (qty >= 0) {
        amount_input.prop('value', qty * unit_price);
        $('#current_selected_total').html(qty * unit_price);
        $('#current_total').html(bal);
    }
});

btn.on('click', function (e) {
    e.preventDefault();
    btn.html('')
    btn.wrapInner('<div class="spinner-border" role="status"><span class="sr-only"></span></div> Processing...');
    setTimeout(function () {
        const amt = amount_input.val();
        if (amt === '0' || quantity_input.val() === '0') {
            console.log("AMOUNT IS 0, QUITTING...");
            mSwal('warning', 'Enter valid amount or quantity');
            btn.html('Invest')
        }else{
            console.log("INVESTING...");
            $('#conf_brocker_fees').html(100);
            $('#conf_quantity').html(quantity_input.val());
            $('#conf_amount').html(quantity_input.val() * unit_price);
            $('#conf_total').html(quantity_input.val() * unit_price + 100);
            $('#investmentModal').modal('show');
            btn.html('Invest');
    }

    }, 500);

});

$('#investment_submit').on('click', function (e) {
    e.preventDefault();
    $.ajax({
        url: '{% url 'trading:buy_shares' %}',
        type: 'POST',
        data: {
            symbol: "{{ share.symbol }}",
            quantity: quantity_input.val(),
            fees: 100
        },
        success: function (data) {
            var d = $.parseJSON(data)[0];
            var url = "{% url 'trading:receipt' pk='1' %}"
            console.log("SUCCESSFUL AJAX REQUEST");
            mSwal('success', 'Successfully Invested');
            $('#investmentModal').modal('hide');
            setTimeout(function () {
                window.location.replace("");
            }, 100);
        },
        error: function (error, exception) {
            console.log("AN ERROR OCCURRED");

            mSwal('error', error.responseText)
        }
    });
});

</script>
{% endblock %}

{% block content %}
  <div class="col-md-12 align-items-start profile-feed-item">
    <div class="row">
      <div class="col-md-8 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-row justify-content-between">
              <div>
                <h4 class="card-title">Invest Now</h4>
              </div>
              <div class="align-self-center">
                <p class="text-muted">View History</p>
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                  <img class="card-img-top" width="30%" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text={{ share.name }} ({{ share.symbol }})" alt="{{ share.name }} image cap">

                  <div class="row">
                      <div class="col-md-6">
                        <div class="py-4">
                          <p class="clearfix">
                            <span class="float-left"> Status </span>
                            <span class="float-right text-muted"> Active </span>
                          </p>
                          <p class="clearfix">
                            <span class="float-left"> Share Price </span>
                            <span class="float-right text-muted"> Ksh. {{ share.current_price }} </span>
                          </p>
                        </div>
                      </div>
                  </div>
                  <hr>
                  <div class="col-md-9 grid-margin stretch-card">
                    <div class="card">
                      <div class="card-body">
                        <h4 class="card-title"> Buy {{ share.name }} Shares </h4>
                        <p class="card-description"> Fill the form below </p>
                        <form class="forms-sample">
                          <div class="form-group">
                            <label for="quantity">Number of Shares To Buy</label>
                            <input required type="number" name="investment_quantity" class="form-control" id="quantity" value="0">
                          </div>
                          <div class="form-group">
                            <label for="amount">Amount To Pay</label>
                            <input required type="number" name="investment_amount" class="form-control" id="amount" value="0">
                          </div>
                          <button type="button" id="invest_button" class="btn btn-primary mr-2">Buy Shares</button>
                          <button class="btn btn-dark">Cancel</button>
                        </form>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Current Balance</h4>
            <div class="row my-4">
              <div class="col-lg-7 mx-auto text-center">
                <div id="currentBalanceCircle" class="progressbar-js-circle demo-progress-circle"></div>
                <h3 class="card-text mb-0 mt-4">Ksh. {{ user.wallet.amount }}</h3>
                <p class="card-text">Current Balance</p>
              </div>
            </div>
            <div class="row mt-3">
              <div class="col-12 bg-gray-dark d-flex flex-row py-3 px-4 rounded justify-content-between">
                <div>
                  <h6 class="mb-1">Total selected</h6>
                </div>
                <div class="align-self-center">
                  <h6 class="font-weight-bold mb-0" id="current_selected_total">Ksh. 0</h6>
                </div>
              </div>
            </div>
            <div class="row mt-3">
              <div class="col-12 bg-gray-dark d-flex flex-row py-3 px-4 rounded">
                <div>
                  <h6 class="mb-1">Balance</h6>
                </div>
                <div class="align-self-center flex-grow text-right">
                  <h6 class="font-weight-bold mb-0" id="current_total">Ksh. {{ user.wallet.amount }}</h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="modal fade" id="investmentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel-3" aria-hidden="true">
      <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel-3">Confirm Investing in {{ share.name }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <img class="card-img-top" width="30%" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text={{ share.name }} ({{ share.symbol }})" alt="{{ share.name }} image cap">
              <div class="row">
                  <div class="col-md-6"></div>
                  <div class="col-md-6">
                    <div class="py-4">
                      <p class="clearfix"><span class="float-left font-weight-bolder"> Account Balance </span><span class="float-right text-muted font-weight-bolder"> Ksh. {{ user.wallet.amount }} </span></p>
                        <hr>
                      <p class="clearfix"><span class="float-left"> Broker Fees </span><span class="float-right text-muted" id="conf_brocker_fees"></span></p>
                      <p class="clearfix"><span class="float-left"> Share Price </span><span class="float-right text-muted"> Ksh. {{ share.current_price }} </span></p>
                      <p class="clearfix"><span class="float-left"> Shares Bought </span><span class="float-right text-muted" id="conf_quantity"></span></p>
                      <p class="clearfix"><span class="float-left"> Amount Paid </span><span class="float-right text-muted" id="conf_amount"></span></p>
                        <hr>
                      <p class="clearfix"><span class="float-left font-weight-bolder"> TOTAL </span><span class="float-right text-muted font-weight-bolder" id="conf_total"></span></p>
                    </div>
                  </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-success" id="investment_submit">Submit</button>
            <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

core/templates/core/shares_list.html
{% extends 'core/index.html' %}
{% load static %}

{% block title %}
List
{% endblock %}

{% block custom_script %}
<script src="{% static 'js/holder.min.js' %}"></script>

    <script type="text/javascript">
    const search_input = $('#company_search');

    search_input.on('input', function () {
        const q = search_input.val();

        $.ajax({
            url: "{% url 'core:search' %}",
            type: 'POST',
            data: {
                q: q
            },
            success: function (data) {
                const res = $.parseJSON(data);
                $('#search_results').html('');

                jQuery.each(res, function (index, value) {
                    var url = "{% url 'core:details' symbol='sm' %}"
                    url = url.replace('sm', value.fields.symbol);
                    $('#search_results').append(

                       '<div class="card">' +
                        '<img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=SYMBOL" alt="' + value.fields.name + ' image cap">' +
                        '<div class="card-body">' +
                        '<h4 class="card-title">' + value.fields.name + '</h4>' +
                        '<p class="card-text">' + value.fields.description + '</p>' +
                        '<div class="py-4">' +
                        '<p class="clearfix">' +
                        '<span class="float-left"> Status </span>' +
                        '<span class="float-right text-muted"> Active </span>' +
                        '</p>' +

                        '<p class="clearfix">' +
                        '<span class="float-left"> Share Price </span>' +
                        '<span class="float-right text-muted"> Ksh. ' + value.fields.current_price + ' </span>' +
                        '</p>' +
                        '</div>' +
                        '<a href="' + url + '"><button class="btn btn-primary btn-block">Select</button></a>' +
                        '</div>' +
                        '</div>'


                    );
                });
            },
            error: function (error, exception){

            }
        });
    });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-6"></div>
        <div class="col-6">
            <form action="#">
                <div class="form-group d-flex">
                    <input type="text" class="form-control" id="company_search" placeholder="Search Here">
                    <button type="submit" class="btn btn-primary ml-3">Search</button>
                </div>
            </form>
        </div>
    </div>
<div class="content-wrapper">
    <div class="card-columns" id="search_results">
        {% for share in shares %}
            <div class="card">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text={{ share.name }} ({{ share.symbol }})" alt="{{ share.name }} image cap">
                <div class="card-body">
                    <h4 class="card-title">{{ share.name }}</h4>
                    <p class="card-text">{{ share.description }}</p>
                    <div class="py-4">
                      <p class="clearfix">
                        <span class="float-left"> Status </span>
                        <span class="float-right text-muted"> Active </span>
                      </p>
                      <p class="clearfix">
                        <span class="float-left"> Share Price </span>
                        <span class="float-right text-muted"> Ksh. {{ share.current_price }} </span>
                      </p>
                    </div>
                    <a href="{% url 'core:details' symbol=share.symbol %}"><button class="btn btn-primary btn-block">Select</button></a>
                </div>
            </div>

        {% endfor %}


    </div>
</div>
{% endblock %}