accounts/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import profile, register
from .forms import UserLoginForm


app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html',
        authentication_form=UserLoginForm
    ), name='login'),
    path('register/', register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),

    path('reset/reset_password/',
         PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='reset_password'),
    path('reset/reset_password_sent/',
         PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/reset_password_complete/',
         PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),
         name='password_reset_complete'),
]

core/urls.py
from django.urls import path

from .views import *


app_name = 'core'
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('charts/', charts, name='charts'),
    path('shares/', shares_view, name='shares'),
    path('shares/search/', search_company, name='search'),
    path('shares/assets/price/', get_asset_price, name='price'),
    path('shares/details/<str:symbol>/', shares_detail, name='details'),
]

trading/urls.py
from django.urls import path

from .views import *


app_name = 'trading'

urlpatterns = [
    path('investments/<int:pk>/receipt/', receipt_view, name='receipt'),
    path('investments/', investment_view, name='investments'),
    path('withdraw/', withdrawals_view, name='withdraw'),
    path('sell/', sell_view, name='sell'),
    path('sell/submit/', sell_shares, name='sell_submit'),
    path('buy/', buy_shares, name='buy_shares'),
]

trustfuse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('', include('core.urls', namespace='core')),
    path('trading/', include('trading.urls', namespace='trading')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    {% include 'head.html' %}

    {% block custom_header %}{% endblock %}
  </head>
  <body>

    {% include 'header.html' %}

    <div class="d-flex align-items-stretch">
      <!-- Sidebar Navigation-->

        {% include 'sidebar.html' %}

      <div class="page-content">
        <div class="page-header">
          <div class="container-fluid">
            <h2 class="h5 no-margin-bottom">{% block page_title %}{% endblock %}</h2>
          </div>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="row ml-2">
                    <div class="col-md-6 col-sm-12">
                        <div class="alert alert-{{ message.tags }}"><strong>{{ message.tags }}: </strong> {{ message }}</div>
                    </div>
                </div>

            {% endfor %}
        {% endif %}
        {% block content %}
            THIS IS THE PAGE CONTENT
        {% endblock %}

        {% include 'footer.html' %}
      </div>
    </div>
    {% include 'scripts.html' %}

  {% block custom_script %}{% endblock %}
  </body>
</html>

templates/footer.html
<!-- partial:partials/_footer.html -->
  <footer class="footer container">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2019 <a href="https://www.bootstrapdash.com/" target="_blank">BootstrapDash</a>. All rights reserved.</span>
      <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
  </footer>
  <!-- partial -->

templates/head.html
{% load static %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- plugins:css -->
<link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
<!-- endinject -->
<!-- Plugin css for this page -->
<link rel="stylesheet" href="{% static 'assets/vendors/jvectormap/jquery-jvectormap.css' %}">
<link rel="stylesheet" href="{% static 'assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
<!-- End plugin css for this page -->
<!-- inject:css -->
<!-- endinject -->
<!-- Layout styles -->
<link rel="stylesheet" href="{% static 'assets/css/classic-horizontal/style.css' %}">
<!-- End layout styles -->
<link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
<link rel="stylesheet" href="{% static 'assets/css/mStyle.css' %}">

templates/header.html
<header class="header">
  <nav class="navbar navbar-expand-lg">
    <div class="search-panel">
      <div class="search-inner d-flex align-items-center justify-content-center">
        <div class="close-btn">Close <i class="fa fa-close"></i></div>
        <form id="searchForm" action="#">
          <div class="form-group">
            <input type="search" name="search" placeholder="What are you searching for...">
            <button type="submit" class="submit">Search</button>
          </div>
        </form>
      </div>
    </div>
    <div class="container-fluid d-flex align-items-start justify-content-between">
      <div class="navbar-header">
        <!-- Navbar Header--><a href="{% url 'core:dashboard' %}" class="navbar-brand">
          <div class="brand-text brand-big visible text-uppercase"><strong class="text-primary">CARE</strong><strong>MAX</strong></div>
          <div class="brand-text brand-sm"><strong class="text-primary">C</strong><strong>M</strong></div></a>
        <!-- Sidebar Toggle Btn-->
        <button class="sidebar-toggle"><i class="fa fa-long-arrow-left"></i></button>
      </div>
        <div class="right-menu list-inline no-margin-bottom">
            <div class="list-inline-item logout"><a id="logout" href="{% url 'accounts:logout' %}" class="nav-link">Logout <i class="icon-logout"></i></a></div>
        </div>
    </div>
  </nav>
</header>

templates/modals.html
<!-- Flexbox container for aligning the toasts -->

templates/navigation.html
{% load static %}

<div class="horizontal-menu">
    <nav class="navbar top-navbar col-lg-12 col-12 p-0">
      <div class="container">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          <a class="navbar-brand brand-logo" href="{% url 'core:dashboard' %}"><img src="{% static 'assets/images/logo.svg' %}" alt="logo" /></a>
          <a class="navbar-brand brand-logo-mini" href="{% url 'core:dashboard' %}"><img src="{% static 'assets/images/logo-mini.svg' %}" alt="logo" /></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
          <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item dropdown border-left">
              <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                <i class="mdi mdi-bell"></i>
                <span class="count bg-danger">7</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                <h6 class="p-3 mb-0">Notifications</h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-calendar text-success"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject mb-1">Event today</p>
                    <p class="text-muted ellipsis mb-0"> Just a reminder that you have an event today </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-settings text-danger"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject mb-1">Settings</p>
                    <p class="text-muted ellipsis mb-0"> Update dashboard </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-link-variant text-warning"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject mb-1">Launch Admin</p>
                    <p class="text-muted ellipsis mb-0"> New admin wow! </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <p class="p-3 mb-0 text-center">See all notifications</p>
              </div>
            </li>
            <li class="nav-item dropdown border-left">
              <a class="nav-link dropdown-toggle" href="#" id="accountDropdown" data-toggle="dropdown">
                <i class="fa-lock gb-primary"></i>
              </a>
                <div class="dropdown-menu navbar-dropdown preview-list" aria-labelledby="accountDropdown">
                <a class="dropdown-item preview-item" href="{% url 'accounts:profile' %}">
                  <div class="preview-item-content">
                    <p class="preview-subject mb-1">Profile</p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item" href="{% url 'accounts:logout' %}">
                  <div class="preview-item-content">
                    <p class="preview-subject mb-1">Logout</p>
                  </div>
                </a>
              </div>
            </li>
            <li class="nav-item nav-settings d-none d-lg-block">
              <a class="nav-link" href="#">
                <i class="mdi mdi-view-grid"></i>
              </a>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="horizontal-menu-toggle">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </div>
    </nav>
    <nav class="bottom-navbar">
      <div class="container">
        <ul class="nav page-navigation">
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'core:dashboard' %}">
              <i class="mdi mdi-speedometer menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'core:shares' %}">
              <i class="mdi mdi-file-restore menu-icon"></i>
              <span class="menu-title">Companies</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'trading:investments' %}">
              <i class="mdi mdi mdi-texture menu-icon"></i>
              <span class="menu-title">Investments</span>
            </a>
          </li>
          <li class="nav-item mega-menu menu-items">
            <a href="{% url 'trading:sell' %}" class="nav-link">
              <i class="mdi mdi-crosshairs-gps menu-icon"></i>
              <span class="menu-title">Sales</span>
              <i class="menu-arrow"></i>
            </a>
          </li>

          <li class="nav-item mega-menu menu-items">
            <a href="{% url 'trading:withdraw' %}" class="nav-link">
              <i class="mdi mdi-crosshairs-gps menu-icon"></i>
              <span class="menu-title">withdrawals</span>
              <i class="menu-arrow"></i>
            </a>
          </li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
        </ul>
      </div>
    </nav>
    </div>

templates/scripts.html
{% load static %}
<!-- plugins:js -->
<script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src="{% static 'assets/vendors/progressbar.js/progressbar.min.js' %}"></script>
<script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
<script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{% static 'assets/js/off-canvas.js' %}"></script>
<script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
<script src="{% static 'assets/js/misc.js' %}"></script>
<script src="{% static 'assets/js/settings.js' %}"></script>
<script src="{% static 'assets/js/todolist.js' %}"></script>
<!-- endinject -->
<!-- Custom js for this page -->
<script src="{% static 'assets/js/dashboard.js' %}"></script>
<!-- End custom js for this page -->

templates/sidebar.html
{% load static %}


      <nav id="sidebar">
        <!-- Sidebar Header-->
        <div class="sidebar-header d-flex align-items-center">
          <div class="avatar"><img src="{% static 'img/avatar-6.jpg' %}" alt="..." class="img-fluid rounded-circle"></div>
          <div class="title">
            <h1 class="h5">{{ user.username }}</h1>
            <p>Logged {{ user.last_login|timesince }} ago</p>
          </div>
        </div>
        <!-- Sidebar Navidation Menus--><span class="heading">Main</span>
        <ul class="list-unstyled">
                <li><a href="{% url 'core:dashboard' %}"> <i class="icon-home"></i>Dashboard </a></li>
                <li><a href="#investmentDropDown" aria-expanded="false" data-toggle="collapse"> <i class="icon-windows"></i>Investment </a>
                      <ul id="investmentDropDown" class="collapse list-unstyled ">
{#                        <li><a href="{% url 'invest' %}">Invest</a></li>#}
{#                        <li><a href="{% url 'plans' %}">Investment History</a></li>#}
                      </ul>
                </li>
{#                <li><a href="#withdrawalDropDown" aria-expanded="false" data-toggle="collapse"> <i class="icon-padnote"></i>Withdrawals </a>#}
{#                    <ul id="withdrawalDropDown" class="collapse list-unstyled ">#}
{#                    <li><a href="{% url 'withdrawals' %}">Withdraw Investment</a></li>#}
{#                    <li><a href="{% url 'bonus_withdrawals' %}">Withdraw Referral Bonus</a></li>#}
{#                  </ul>#}
{#                </li>#}
{#                <li><a href="#profileDropDown" aria-expanded="false" data-toggle="collapse"> <i class="icon-windows"></i>Profile </a>#}
{#                  <ul id="profileDropDown" class="collapse list-unstyled ">#}
{#                    <li><a href="{% url 'accounts:profile' %}">Profile</a></li>#}
{##}
{#                  </ul>#}
{#                </li>#}
{#            {% if user.is_staff %}#}
{##}
{#                <li><a href="#adminDropDown" aria-expanded="false" data-toggle="collapse"> <i class="icon-windows"></i>ADMIN </a>#}
{#                  <ul id="adminDropDown" class="collapse list-unstyled ">#}
{#                    <li><a href="{% url 'withdraw-requests' %}">Withdrawal Requests</a></li>#}
{#                    <li><a href="{% url 'add-payment' %}">Add Payment</a></li>#}
{#                    <li><a href="/admin/">Admin Management</a></li>#}
{#                  </ul>#}
{#                </li>#}
{#            {% endif %}#}

        </ul><span class="heading">Extras</span>
          <ul class="list-unstyled">
              <li><a target="_blank" href="{{ whatsapp_link }}"> <i class="icon-padnote"></i>Whatsapp </a></li>
              <li><a href="{% url 'accounts:logout' %}"> <i class="icon-logout"></i>Logout </a></li>
          </ul>
      </nav>
      <!-- Sidebar Navigation end-->