core/urls.py
from django.urls import path

from .views import *


app_name = 'core'
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('charts/', charts, name='charts'),
    path('shares/', shares_view, name='shares'),
    path('shares/search/', search_company, name='search'),
    path('shares/assets/price/', get_asset_price, name='price'),
    path('shares/details/<str:symbol>/', shares_detail, name='details'),
]

trading/urls.py
from django.urls import path

from .views import *


app_name = 'trading'

urlpatterns = [
    path('investments/<int:pk>/receipt/', receipt_view, name='receipt'),
    path('investments/', investment_view, name='investments'),
    path('withdraw/', withdrawals_view, name='withdraw'),
    path('sell/', sell_view, name='sell'),
    path('sell/submit/', sell_shares, name='sell_submit'),
    path('buy/', buy_shares, name='buy_shares'),
]

trustfuse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('', include('core.urls', namespace='core')),
    path('trading/', include('trading.urls', namespace='trading')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trading/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from core.models import Share


class WithdrawStatus(models.IntegerChoices):

    PENDING = 0, _('Pending')
    APPROVED = 1, _('Approved')
    COMPLETED = 2, _('Completed')
    REJECTED = 3, _('Rejected')


class Base(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Investment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    share = models.ForeignKey(Share, on_delete=models.CASCADE, default=1)
    quantity = models.IntegerField(default=1)
    amount = models.FloatField()
    fees = models.FloatField(default=0)
    current_price = models.FloatField(default=0)
    investment_date = models.DateTimeField(default=timezone.now)

    def cost(self):
        return self.current_price * self.quantity

    def total_paid(self):
        return self.cost() + self.fees

    def net_earning(self):
        share_value = self.share.current_price
        return (share_value * self.quantity + self.fees) - (self.total_paid())


class Withdrawal(Base):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    amount = models.FloatField()
    status = models.IntegerField(choices=WithdrawStatus.choices, default=WithdrawStatus.PENDING)
    status_by = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='approver', null=True, blank=True)
    date_of_approval = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.user.username


class SoldShares(Base):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    share = models.ForeignKey(Share, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    amount_received = models.FloatField()

    def __str__(self):
        return self.user.username

trading/views.py
from core.utils import Account
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

from core.models import Share
from trading.models import Investment, Withdrawal, SoldShares


@csrf_exempt
def buy_shares(request):
    if request.is_ajax():
        print(f'Incoming Request: {request.POST}')
        quantity = int(request.POST['quantity'])
        fees = int(request.POST['fees'])
        symbol = request.POST['symbol']

        share = Share.objects.get(symbol=symbol)
        user = request.user

        if quantity < 1:
            return HttpResponse('Shares bought cannot be 0',
                                status=HttpResponseBadRequest.status_code)

        unit_price = share.current_price
        amount = unit_price * quantity

        if amount + fees > user.wallet.amount:
            return HttpResponse('Not enough balance to invest this amount. Try a lower amount or deposit first',
                                status=HttpResponseBadRequest.status_code)
        investment = Investment.objects.create(
            user=user,
            amount=amount,
            share=share,
            quantity=quantity,
            fees=fees,
            current_price=share.current_price
        )
        return JsonResponse(data=serializers.serialize('json', [investment, ]), safe=False)


@login_required
def investment_view(request):
    invs = Investment.objects.filter(user=request.user)
    context = {
        'investments': invs
    }
    return render(request, 'trading/investments.html', context)


@login_required
def receipt_view(request, pk):
    try:
        inv = Investment.objects.get(pk=pk)
    except Investment.DoesNotExist:
        return redirect('trading:investments')
    return render(request, 'trading/receipt.html', {'investment': inv})


@login_required
def withdrawals_view(request):
    if request.method == 'POST':
        amount = int(request.POST['amount'])
        if 0 < amount <= request.user.wallet.amount:
            Withdrawal.objects.create(
                user=request.user,
                amount=amount,
            )
            messages.success(request, f'Successfully Withdrawn Ksh. {amount}')
            return redirect('trading:withdraw')
        else:
            messages.warning(request, "Invalid amount or not enough balance. Please try again later.")
    w = Withdrawal.objects.filter(user=request.user)
    context = {
        'withdrawals': w
    }
    return render(request, 'trading/withdrawals.html', context=context)


@csrf_exempt
def sell_shares(request):
    if request.is_ajax():
        asset = request.POST['asset']
        quantity = int(request.POST['quantity'])
        try:
            share = Share.objects.get(symbol=asset)
        except Share.DoesNotExist:
            return HttpResponse('Invalid Asset Selected.', HttpResponseBadRequest.status_code)
        # asst_qty = request.user.investment_set.filter(share=share).aggregate(Sum('quantity'))['quantity__sum'] or 0
        # print(asst_qty)
        acc = Account(request.user)
        asst_qty = 0
        for ast in acc.balance():
            if ast['share__symbol'] == share.symbol:
                asst_qty = ast['total_items']
                # print(f"asset {ast['share_symbol']} -> {ast['total_items']}")
                
        if 0 < quantity <= asst_qty:
            SoldShares.objects.create(
                user=request.user,
                share=share,
                quantity=quantity,
                amount_received=share.current_price * quantity
            )
            return HttpResponse(
                f"Successfully sold {quantity} {share.name} shares Worth Ksh. {share.current_price * quantity}",
                200
            )
        return HttpResponse(
            f"Invalid quantity. Either you dont have enough {share.name} shares or you entered invalid amount. Try again",
            HttpResponseBadRequest.status_code
        )


@login_required
def sell_view(request):
    acc = Account(request.user)
    items = [i for i in acc.balance() if i['total_items'] > 0]
    names = [i['share__symbol'] for i in items]

    context = {
        'shares': items,
        'names': names,
        'value': acc.value()
    }
    return render(request, 'trading/sell.html', context)

trading/templates/trading/investments.html
{% extends 'core/index.html' %}

{% block title %}
    Investments
{% endblock %}

{% block content %}
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">My Investments</h4>
            <p class="card-description"><code>Investments you have made</code>
            </p>
            <div class="table-responsive">
              <table class="table table-dark">
                <thead>
                  <tr>
                    <th> # </th>
                    <th> Date </th>
                    <th> Name </th>
                    <th> Symbol </th>
                    <th> Price when purchasing </th>
                    <th> Quantity Purchased </th>
                    <th> Total Amount </th>

                  </tr>
                </thead>
                  <tbody>

                  {% for investment in investments %}
                      <tr>
                          <td> {{ forloop.counter }} </td>
                          <td> {{ investment.investment_date|timesince }} ago </td>
                          <td> {{ investment.share.name }} </td>
                          <td> {{ investment.share.symbol }} </td>
                          <td> Ksh. {{ investment.current_price }} </td>
                          <td> {{ investment.quantity }} {% if investment.quantity == 1 %} share {% else %} shares {% endif %}</td>
                          <td> Ksh. {{ investment.total_paid }} </td>
                      </tr>
                {% endfor %}


                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

trading/templates/trading/receipt.html
{% extends 'core/index.html' %}

{% block content %}
<div class="row">
  <div class="col-lg-12">
    <div class="card px-2">
      <div class="card-body">
        <div class="container-fluid">
          <h3 class="text-right my-5">Invoice&nbsp;&nbsp;#INV-{{ investment.pk }}</h3>
          <hr>
        </div>
        <div class="container-fluid d-flex justify-content-between">
          <div class="col-lg-3 pl-0">
            <p class="mt-5 mb-2"><b>Trustfuse Admin</b></p>
            <p>104,<br>Chuka,<br>Kenya</p>
          </div>
          <div class="col-lg-3 pr-0">
            <p class="mt-5 mb-2 text-right"><b>Invoice to</b></p>
            <p class="text-right">{{ investment.user.username }},<br> {{ investment.user.email }},<br> Kenya.</p>
          </div>
        </div>
        <div class="container-fluid d-flex justify-content-between">
          <div class="col-lg-3 pl-0">
            <p class="mb-0 mt-5">Receipt Date : {{ investment.investment_date }}</p>

          </div>
        </div>
        <div class="container-fluid mt-5 d-flex justify-content-center w-100">
          <div class="table-responsive w-100">
            <table class="table">
              <thead>
                <tr class="bg-dark text-white">
                  <th>#</th>
                  <th>Name</th>
                  <th>Symbol</th>
                  <th class="text-right">Quantity</th>
                  <th class="text-right">Unit cost</th>
                  <th class="text-right">Total</th>
                </tr>
              </thead>
              <tbody>
                <tr class="text-right">
                  <td class="text-left">1</td>
                  <td class="text-left">{{ investment.share.name }}</td>
                  <td class="text-left">{{ investment.share.symbol }}</td>
                  <td>{{ investment.quantity }}</td>
                  <td>{{ investment.current_price }}</td>
                  <td>{{ investment.cost }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="container-fluid mt-5 w-100">
          <p class="text-right mb-2">Sub - Total amount: {{ investment.cost }}</p>
          <p class="text-right">Fees : 100</p>
          <h4 class="text-right mb-5">Total : {{ investment.total_paid }}</h4>
          <hr>
        </div>
        <div class="container-fluid w-100">
          <a href="#" class="btn btn-primary float-right mt-4 ml-2"><i class="mdi mdi-printer mr-1"></i>Print</a>
          <a href="#" class="btn btn-success float-right mt-4"><i class="mdi mdi-telegram mr-1"></i>Send Invoice</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

trading/templates/trading/sell.html
{% extends 'core/index.html' %}
{% load static %}

{% block content %}

<div class="row">


  <div class="col-md-4 grid-margin">
    <div class="card">
      <div class="card-body">
        <div class="col-12 d-flex flex-row py-3 px-4 rounded justify-content-between">
          <div><h6 class="mb-1">Account Balance</h6><p class="card-text"></p></div>
          <div class="align-self-center"><h6 class="font-weight-bold mb-0">Ksh. {{ user.wallet.amount }}</h6></div>
        </div>
      </div>
    </div>
  </div> 


  <div class="col-md-4 grid-margin">
    <div class="card">
      <div class="card-body">
        <div class="col-12 d-flex flex-row py-3 px-4 rounded justify-content-between">
          <div><h6 class="mb-1">Assets Value</h6><p class="card-text"></p></div>
          <div class="align-self-center"><h6 class="font-weight-bold mb-0">Ksh. {{ value }}</h6></div>
        </div>
      </div>
    </div>
  </div>

</div>

<div class="row grid-margin">
  <div class="col-lg-12">
    <div class="card px-3">
      <div class="card-body">
        <h4 class="card-title">SELL SHARES</h4>

            <div class="row">
                <div class="col-md-8">

                    <div class="card m-2">
                      <div class="card-body">
                        <h4 class="card-description"> Fill the form below </h4>
                          <hr>
                        <form class="forms-sample">
                          <div class="form-group">
                            <label for="sell_choices">Asset</label>
                              <select class="form-control text-white" id="sell_choices">
                                {% for share in shares %}
                                  <option value="{{ share.share__symbol }}"> {{ share.share__name }}</option>
                                {% endfor %}
                            </select>
                          </div>
                          <div class="form-group">
                            <label for="sell_quantity">Number of Shares To Sell</label>
                            <input required type="number" name="quantity" class="form-control text-white" id="sell_quantity" value="0">
                          </div>
                          <div class="form-group">
                            <label for="sell_amount">Amount To Pay</label>
                            <input required type="number" name="amount" class="form-control" id="sell_amount" value="0">
                          </div>
                          <button type="button" id="sell_button" class="btn btn-primary mr-2">Sell Shares</button>
                          <button class="btn btn-dark">Cancel</button>
                        </form>
                      </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card m-2">
                      <div class="card-body">
                        <h4 class="card-title">Account Information</h4>
                        <p class="card-description"><code class="text-primary">Summary of Shares you hold</code></p>
                        <p class="card-description">BALANCE:  <code class="text-primary">Ksh. {{ user.wallet.amount }}</code></p>
                        <div class="template-demo">
                          <table class="table mb-0">
                            <thead>
                              <tr>
                                <th class="pl-0 text-info">Name</th>
                                <th class="text-right text-danger">Shares Count</th>
                              </tr>
                            </thead>
                            <tbody>

                            {% for share in shares %}

                                <tr>
                                    <td class="pl-0">
                                      <div class="text-primary">{{ share.share__name }}</div>
                                    </td>
                                    <td class="pr-0 text-right">
                                      <div class="text-danger">{{ share.total_items }}</div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                </div>
            </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block custom_script %}
<script src="{% static 'assets/js/alerts.js' %}"></script>
<script src="{% static 'assets/vendors/sweetalert/sweetalert2.all.min.js' %}"></script>
<script type="text/javascript">

{# DEFINING VARIABLES #}
let unit_price = 0;
let amount_input = $('#sell_amount');
const quantity_input = $('#sell_quantity');
const asset = $('#sell_choices');
const user_balance = {{ user.wallet.amount }};
const amt = amount_input.val();
const btn = $('#sell_button');
let mSwal = function(type, message) {
    'use strict';
    Swal.fire({
        title: type + "!",
        text: message,
        icon: type,
    });

  }

let makeAjax = function () {
    $.ajax({
        url: "{% url 'core:price'  %}",
        type: "POST",
        data: {
            q: asset.val()
        },
        success: function (data) {
            let d = $.parseJSON(data);
            amount_input.prop('value', quantity_input.val() * d);
        },
        error: function (error, exception) {
            console.log(error.responseText);
        }
    });

};
asset.on('change', function () {
    makeAjax();
});
quantity_input.on('input', function(e) {
    makeAjax();
});
quantity_input.on('input', function (e) {
    const qty = quantity_input.val();
    if (qty >= 0) {
        amount_input.prop('value', qty * unit_price);
    }
});

btn.on('click', function (e) {
    e.preventDefault();
    const amt = amount_input.val();
    if (amt === '0') {
        console.log("AMOUNT IS 0, QUITTING...");
        mSwal('warning', 'Enter valid amount');
    }else{
      btn.prop('disabled', true);
      btn.wrapInner('<div class="spinner-border" role="status"><span class="sr-only"></span></div> Processing...');
  
      console.log("INVESTING...");

      $.ajax({
        url: "{% url 'trading:sell_submit' %}",
        type: 'POST',
        data: {
          asset: asset.val(),
          quantity: quantity_input.val()
        },
        success: function (data) {
          mSwal('success', data);
          console.log(data);
          console.log("success...");
          btn.html('Sell');
          btn.prop('disabled', false);
          setTimeout(function () {
          
            location.reload();
          }, 500);
            
        },
        error: function (error, exception) {
          console.log("error...");
          btn.html('Sell');
          btn.prop('disabled', false);
          console.log(error.responseText);
        }
      });
    }
});


</script>
{% endblock %}

trading/templates/trading/withdrawals.html
{% extends 'core/index.html' %}

{% block content %}

{#    <div class="text-center">#}
{#      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModal-3">Click for demo<i class="mdi mdi-play-circle ml-1"></i></button>#}
{#    </div>#}
    <div class="modal fade" id="exampleModal-3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel-3" aria-hidden="true">
      <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <form method="post">
                {% csrf_token %}
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel-3">Make Withdrawal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p class="card-description"> Enter Amount To withdraw </p>
                <div class="form-group">
                  <label for="withdrawal_amount">Amount</label>
                  <input type="number" class="form-control" id="withdrawal_amount" name="amount" placeholder="amount">
                </div>
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-success">Submit</button>
                <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
              </div>
            </form>
        </div>
      </div>
    </div>





{#  <div class="col-md-6 grid-margin stretch-card">#}
{#    <div class="card">#}
{#      <div class="card-body">#}
{#        <h4 class="card-title">Withdraw Funds</h4>#}
{#        <p class="card-description"> Enter Amount To withdraw </p>#}
{#        <form class="forms-sample">#}
{#          <div class="form-group">#}
{#            <label for="exampleInputUsername1">Amount</label>#}
{#            <input type="text" class="form-control" id="amount" placeholder="Username">#}
{#          </div>#}
{##}
{#          <button type="submit" class="btn btn-primary mr-2">Submit</button>#}
{#          <button class="btn btn-dark">Cancel</button>#}
{#        </form>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}

<div class="row">


  <div class="col-md-4 grid-margin">
    <div class="card">
      <div class="card-body">
        <div class="col-12 d-flex flex-row py-3 px-4 rounded justify-content-between">
          <div><h6 class="mb-1">Account Balance</h6><p class="card-text"></p></div>
          <div class="align-self-center"><h6 class="font-weight-bold mb-0">Ksh. {{ user.wallet.amount }}</h6></div>
        </div>
      </div>
    </div>
  </div> 

</div>

    <div class="card">
        <div class="card-header ml-2">
            <span class="card-title">WITHDRAWAL HISTORY</span>
            <div class="float-right"><span class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal-3">Make Withdrawal</span></div>
        </div>
        <div class="card-body">

          <hr>
        <div class="row">
          <div class="col-12">
            <div class="table-responsive">
              <table id="order-listing" class="table">
                <thead>
                  <tr>
                    <th> # </th>
                    <th>Amount</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Receiving Phone</th>
                  </tr>
                </thead>
                <tbody>
                  {% for withdrawal in withdrawals %}
                    <tr>
                      <td>{{ forloop.counter }}</td>
                      <td>{{ withdrawal.amount }}</td>
                      <td>{{ withdrawal.date_created }}</td>
                      <td><label class="badge badge-info">Completed</label></td>
                      <td>{{ request.user.profile.phone }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}